@host = http://localhost:5300

### ساخت بازی
POST {{host}}/api/Game/create
Content-Type: application/json

{
  "players": [
    { "id": "p1", "name": "A", "startTileId": "start-A" },
    { "id": "p2", "name": "B", "startTileId": "start-B" }
  ]
}